services:
  django:
    build:
      context: ./GriseldaStudioAPI
      dockerfile: ./compose/dokploy/web/Dockerfile
    ports:
      - '445:445'
    volumes:
      - ./GriseldaStudioAPI/media:/app/media
      - ./GriseldaStudioAPI/staticfiles:/app/staticfiles
      - ./GriseldaStudioAPI/logs:/app/logs
      - gstudio_db:/app/GriseldaStudioAPI/db
    env_file:
      - ./.env

  frontend:
    build:
      context: ./GriseldaStudioCLIENT
    ports:
      - '82:82'
    depends_on:
      - django

volumes:
  gstudio_db: