services:
  django:
    build:
      context: ./GriseldaStudioAPI
      dockerfile: ./compose/dokploy/web/Dockerfile
    volumes:
      - media:/app/media
      - staticfiles:/app/staticfiles
      - logs:/app/logs
    env_file:
      - ./.env

  frontend:
    build:
      context: ./GriseldaStudioCLIENT
    depends_on:
      - django
volumes:
  media:
  staticfiles:
  logs: