services:
  django:
    build:
      context: ./GriseldaStudioAPI
      dockerfile: ./compose/dokploy/web/Dockerfile
    ports:
      - '445:443'
    volumes:
      - ./GriseldaStudioAPI/media:/app/media
      - ./GriseldaStudioAPI/staticfiles:/app/staticfiles
      - ./GriseldaStudioAPI/logs:/app/logs
    env_file:
      - ./.env

  frontend:
    build:
      context: ./GriseldaStudioCLIENT
    ports:
      - '80:80'
    depends_on:
      - django