# Generated by Django 5.0.6 on 2024-06-23 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_categoria', '0002_alter_categoria_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('slug', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('precio_oferta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de oferta')),
                ('imagen', models.ImageField(upload_to='img/productos/', verbose_name='Imagen')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_categoria.categoria', verbose_name='Categoría')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
