# Generated by Django 5.0.6 on 2024-06-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_producto', '0002_alter_producto_descripcion_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
