# Generated by Django 5.0.6 on 2024-06-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/%Y/%m/', verbose_name='Image'),
        ),
    ]
