"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from config.db import BDCONFIG

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOGS_DIR = os.path.join(BASE_DIR, 'logs')

# Crear el directorio de logs si no existe
if not os.path.exists(LOGS_DIR):
  os.makedirs(LOGS_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8=dsd75k*p753i)4^!&bopq+i0#yw=^l9uuu9r%z*i)kn6j43a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOWED_ORIGINS = [
  "http://localhost:5173",
  "http://localhost:80",
  "http://localhost"
]

# Application definition
LIBS_APPS = [
  'django_filters',
  'rest_framework',
  'corsheaders',
  "rest_framework_simplejwt",
]

LOCAL_APPS = [
  'core',
  'core.user',
  'core.auth',
  'core.categoria',
  'core.producto'
]

DEFAULT_APPS = [
  'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres'
]

INSTALLED_APPS = DEFAULT_APPS + LIBS_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = BDCONFIG


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-419'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Configuración de archivos estáticos con WhiteNoise
STATIC_URL = '/static/'

# Ubicación donde se recopilarán los archivos estáticos en producción
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Para habilitar compresión y caching de WhiteNoise
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Si tienes archivos estáticos en directorios locales
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (Images, Videos, etc)
if not 'WEBSITE_HOSTNAME' in os.environ:
  MEDIA_ROOT = os.path.join(BASE_DIR,'media')

#link de como se accede a ellos de forma publica
MEDIA_URL = 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core_user.User'

# COnfiguración Azure
# url blob azure
# URL_STORAGE_AZURE=os.environ.get("URL_STORAGE_AZURE")

# blob azure
# STATIC_URL_AZURE=URL_STORAGE_AZURE+"static/"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    # "PAGE_SIZE": 15,
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
}

APPEND_SLASH = False

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} [{thread:d}] [{module}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
        'request': {
            'format': '[{levelname}] {asctime} {message}',
            'style': '{',
        },
        'error': {
            'format': '[{levelname}] {asctime} [{thread:d}] [{module}] {message}\n{pathname}:{lineno}\n{exc_info}',
            'style': '{',
        }
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file_general': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'when': 'midnight',
            # 'backupCount': 30,  # Mantener logs de los últimos 30 días
            'formatter': 'verbose',
        },
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'errors.log'),
            'when': 'midnight',
            # 'backupCount': 30,  # Mantener logs de errores de los últimos 30 días
            'formatter': 'error',
        },
        'file_requests': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'requests.log'),
            'when': 'midnight',
            # 'backupCount': 7,  # Mantener logs de peticiones de la última semana
            'formatter': 'request',
        },
        'file_api': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'api.log'),
            'when': 'midnight',
            # 'backupCount': 7,  # Mantener logs de API de la última semana
            'formatter': 'request',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'error',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_general'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file_requests', 'file_errors', 'console', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['file_requests', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.template': {
            'handlers': ['file_general', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['file_general', 'console'],
            'level': 'INFO',  # Cambiar a DEBUG para ver todas las consultas SQL
            'propagate': False,
        },
        'django.security': {
            'handlers': ['file_errors', 'console', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        # Logger para API
        'api': {
            'handlers': ['console', 'file_api', 'file_errors'],
            'level': 'DEBUG',
            'propagate': False,
        }
    }
}

# URL del sitio
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')