services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8001 config.wsgi:application
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8001:8001"
    env_file:
      - .env
