version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8001 config.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: griselda_studio_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d root"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
