# Generated by Django 5.0.6 on 2024-06-16 06:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
