# Generated by Django 5.0.6 on 2024-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
